handle zero range step
zslayton/cron pull request #110
Opened 2022-09-22 23:53 UTC by sqwishy

see #105

2022-09-22 23:54 UTC, sqwishy commented
The error message doesn't actually bubble up, looks like it gets swallowed in parsing.rs:25 or so
```
            Err(_) => Err(ErrorKind::Expression("Invalid cron expression.".to_owned()).into()), //TODO: Details
```

2022-09-23 13:47 UTC, zslayton requested changes

2022-09-23 16:11 UTC, sqwishy commented on tests/lib.rs
> +        assert_eq!("Invalid expression: Invalid cron expression.", Schedule::from_str(expression).unwrap_err().to_string());
> which is used in the other tests that expect a failure.

Oops, I definitely tried to use the neighbouring code as a guideline but most have forgotten or just totally missed those tests but you're right.

2022-09-24 01:27 UTC, zslayton approved these changes
Thanks for the contribution!

2022-09-24 01:28 UTC, merged